[package]
name = "O2Build"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.10"
debug_tree = "0.4"
cranelift = "0.79.1"
cranelift-module = "0.79.1"
cranelift-object = "0.79.1"
target-lexicon = "0.12.2"
