[package]
name = "O2Build"
version = "0.1.0"
edition = "2021"

[lib]
name = "Oxygen"

[dependencies]
itertools = "0.10.3"
debug_tree = "0.4.0"
cranelift = "0.80.0"
cranelift-module = "0.80.0"
cranelift-object = "0.80.0"
target-lexicon = "0.12.2"
